[project]
name = "nbac"
version = "0.1.0"
description = "A simple Python package for Naive Bayes archetype classification (NBAC)."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "cloudflare",
  "idna>=3.15",
  "psycopg2-binary",
  "python-dotenv>=1.2.2", # optional
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
